management.endpoints.web.exposure.include=*

spring.application.name=jersey-demo

spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.sql.init.mode=always

